### ISSUE TITLE
Problem with master-branch but not with develop-branch 

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp-ui#10]
When I try to start the master-branch-version, localhost:3000 gives the following response (in a browser-window):

Cannot GET /

To reproduce:

- Delete all cache (or start a incognito-tab) 
- Start the master-branch 
- Surf to localhost:3000

The problem doesn't seem to occur in the develop-branch.

**Comment by danielsneijers** [comment]
Hi Josh, thanks for the heads up. I don't know how this bug slipped in but I will investigate and come back at you later.

**Comment by danielsneijers** [comment]
I'm afraid I can't reproduce this, do you have more specific information regarding this bug? Like what version of Vamp are you running? Are you using the docker-build or are you running on marathon? Does the info endpoint (vamp-url/api/v1/info) respond? Is node serving the UI correctly? (be sure to check that `npm start` doesn't return any errors)

**Comment by JoshFalken** [comment]
Thanks, I know see my error. I always started my backend with 'gulp serve', this also works but only after you ran 'npm start' one time. I forgot to run 'npm start' after the fresh install. Will use 'npm start' from now on. Case closed :-)

**Comment by danielsneijers** [comment]
Glad it worked out!
