### ISSUE TITLE
When artifact creation/editing fails stay on the same page

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#102]
This is tested on breed and blueprint creation pages - when content is not well-formed (valid YAML, but not according to Vamp DSL) then we get an error but also go to list page. There is no possibility to edit original content anymore. In case of edit, it stays on edit page for breeds but not for blueprints (same as for create).
Example of non well-formed breed:
```yaml
name: test
depl: test # instead of deployable
```

**Comment by brniamut** [comment]
List of views where this should be implemented.
- [ ]  createBlueprint
- [ ]  createBreed
- [ ]  createGateway
- [ ]  createWorkflow
- [ ]  updateBlueprint
- [ ] updateBreed
- [ ] updateDeployment
- [ ] updateGateway
- [ ] updateWorkflow
