### ISSUE TITLE
Can we show how many req/s and the response time per route is actually delivered to each route?

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#108]
in gateway detail screen it would be nice to show the realtime numbers of req/s that are routed to every route, and it's response time. These can be added to every route row.

**Comment by brniamut** [comment]
Is this not now solved with the sparkline implementation (issue #67)?

**Comment by olafmol** [comment]
Can we show numerics by hovering over the sparkline? If so: yes, if not: a realtime numeric metric per route would still be useful. If we run out of screen space I would suggest a mouse over tooltip/panel.

**Comment by brniamut** [comment]
<img width="510" alt="screenshot 2016-08-31 14 49 47" src="https://cloud.githubusercontent.com/assets/2960616/18129268/465deb8e-6f8a-11e6-8ce0-27b82cd247c8.png">

I think I don't understand the issue. The number are there. Or do you mean an other value?

**Comment by olafmol** [comment]
It's ok this way!
