### ISSUE TITLE
highlight changes in detail pages

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#110]
when f.e. scale numbers or routing percentages change (triggered by a workflow or something else) we should highlight the field temporary, so it's easy to detect visually what has changed

**Comment by brniamut** [comment]
4d7f2d0da15eedfe0e16667d9d0b603d1af0099e makes this work on the single gateway screen. Right now the implementation will only work for single values and not on a refresh of a whole array. 

If the datahandling is refactored (see issue #68) it will work for the other values automatically.  I will leave the issue open.
