### ISSUE TITLE
Response time on chart may have a negative value

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#119]
![screen shot 2016-08-30 at 18 39 47](https://cloud.githubusercontent.com/assets/7957524/18099141/76d8db70-6ee5-11e6-9030-00ce232fa072.png)

**Comment by brniamut** [comment]
Has to do with the calculation of bezier-curve of the graph. Only a newer version of chart.js supports the cutting off of the curve. This version does not work with the current version of angular-chart. I found a work around for now.
