### ISSUE TITLE
Add toggle filters for events 

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#142]
Example for `health` and `metrics` filters:

![screen shot 2016-09-29 at 11 10 01](https://cloud.githubusercontent.com/assets/7957524/18948978/8cc438f6-8639-11e6-9fbf-ec9734029658.png)

**Comment by olafmol** [comment]
i would suggest adding a textual filter box as it gives us much more flexibility. We could even populate it with default labels like health / metrics. If this filter box could also filter on tags and type that would be even more helpful

**Comment by dragoslav** [comment]
done in `ws` branch.
