### ISSUE TITLE
Integrate with Mixpanel statistics

### ISSUE THREAD

**Issue by brniamut** [magneticio/vamp-ui#15]
<a href="https://github.com/olafmol"><img src="https://avatars.githubusercontent.com/u/355268?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [olafmol](https://github.com/olafmol)**
_Sunday Mar 06, 2016 at 22:09 GMT_
_Originally opened as https://github.com/magneticio/revamp-ui/issues/7_

----

GUI events should be logged to Mixpanel for analytics/stats of UI usage

**Comment by brniamut** [comment]
<a href="https://github.com/mscholtus"><img src="https://avatars.githubusercontent.com/u/214612?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mscholtus](https://github.com/mscholtus)**
_Monday Mar 07, 2016 at 12:03 GMT_

----

Can we use the mixpanel settings from the current UI? As seen in: https://github.com/magneticio/vamp-ui/blob/585bef00d6d6fd73adb23a3d028eafa55b0b5637/src/www/index.html

**Comment by brniamut** [comment]
<a href="https://github.com/dragoslav"><img src="https://avatars.githubusercontent.com/u/7957524?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dragoslav](https://github.com/dragoslav)**
_Monday Mar 07, 2016 at 12:07 GMT_

----

Yes in the beginning - it will provide something we have now. 
We should combine it with https://github.com/magneticio/vamp/issues/510

**Comment by brniamut** [comment]
<a href="https://github.com/dragoslav"><img src="https://avatars.githubusercontent.com/u/7957524?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dragoslav](https://github.com/dragoslav)**
_Wednesday Jun 08, 2016 at 12:33 GMT_

----

Take a look at `/api/v1/statistics` response

**Comment by olafmol** [comment]
I do see a whole bunch of "UI loaded" events after each other, let's check if they are not generated by a loop, and if all the events that can be generated are correctly logged in Mixpanel.

**Comment by brniamut** [comment]
Hey Olaf, this is because with every codechange the ui reloads in the browser. So when developing, it will give a lot of UI Loaded events.

Solution is filtering in mixpanel on anything that is not localhost. That's how you can see difference between environments. This is expected behaviour.

**Comment by brniamut** [comment]
Or we could turn mixpanel off when the environment is development. That might even be a better and cleaner solution.

**Comment by olafmol** [comment]
ok understood!

**Comment by dragoslav** [comment]
@brniamut as you suggested, it should be disabled during development.
