### ISSUE TITLE
external gateway detail screen shows "not HTTP" as sticky status by default

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#173]
even though the external gateway is HTTP:

<img width="1257" alt="screen shot 2016-10-28 at 00 06 41" src="https://cloud.githubusercontent.com/assets/355268/19787366/9459fa18-9ca2-11e6-90c4-1450cd1eb940.png">

**Comment by dragoslav** [comment]
Fixed for HTTP, but there is still an issue related to TCP https://github.com/magneticio/vamp/issues/810
