### ISSUE TITLE
Show delete results in UI immediately 

### ISSUE THREAD

**Issue by brniamut** [magneticio/vamp-ui#18]
<a href="https://github.com/olafmol"><img src="https://avatars.githubusercontent.com/u/355268?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [olafmol](https://github.com/olafmol)**
_Thursday Jul 21, 2016 at 08:30 GMT_
_Originally opened as https://github.com/magneticio/revamp-ui/issues/69_

----

when the API returns OK when requesting a DELETE action, we update the UI presentation of items immediately. Polling to backend will happen later and could update the list according to backend data-set accordingly.

**Comment by olafmol** [comment]
this doesn't happen when undeploying, is this by design? (in all other pages it works fine)

**Comment by olafmol** [comment]
depending on impact of implementation we can postpone/cancel this. Please discuss, its no blocker

**Comment by dragoslav** [comment]
Undeploying takes some time - and it should disappear once it's done. What we can show is that it is in progress.
