### ISSUE TITLE
Text in yellow boxes hard to read

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp-ui#180]
The text in the yellow boxes need to be adjusted to make it easier to read.

![bad-yellow.png](https://zube.io/files/magneticio/2fe0a9283de31eb4f97c1fc504523609.png)
![bad-yellow_2.png](https://zube.io/files/magneticio/a895b49cd45b556aa0aec37728a4e6a2.png)

**Comment by olafmol** [comment]
we need to make the bright yellow/orange background darker so the contrast with the white text on top of it is better.
