### ISSUE TITLE
interface is getting crowded

### ISSUE THREAD

**Issue by harmw** [magneticio/vamp-ui#182]
Looking at the available/installed gateways, here's what I get:
<img width="1810" alt="schermafbeelding 2016-11-28 om 16 49 29" src="https://cloud.githubusercontent.com/assets/5871646/20674879/b6accae0-b58a-11e6-9ae3-b10b1f60084d.png">

I'm installing a gateway per service, and when running an upgrade there will be 2 versions (ports) attached to it. As you can see, this is completely useless once we move to having like 40 to 50 services deployed. The same is ofcourse true for other overview pages.

Can we get this page to be more like Marathon's services list?

**Comment by olafmol** [comment]
assigning this for now to @DHVAMP to improve UI for higher numbers of items

**Comment by olafmol** [comment]
List view design as an alternative for grid view:

[VAMP-UI-0.9.2-listview.pdf](https://github.com/magneticio/vamp-ui/files/682508/VAMP-UI-0.9.2-listview.pdf)

**Comment by eyal-magnetic** [comment]
@olafmol @DHVAMP 
Need some behaviour details of the attached pagination design.

**Comment by DHVAMP** [comment]
New pagination setup. We need tot decide though what we want to do with a bigger amount of pages. 

![pagination](https://cloud.githubusercontent.com/assets/20397075/22106860/1a7d731a-de4b-11e6-8c20-51462c891d48.png)

**Comment by olafmol** [comment]
Let's do a MVP release first: no complex logic, just a "simple" row of pagination links that fit in the screen width. We can finetune and extend later on.

**Comment by eyal-magnetic** [comment]
New implementation of list view:

![image](https://cloud.githubusercontent.com/assets/24912601/22155276/22ff0776-df2f-11e6-9c89-f08ce1d41802.png)
