### ISSUE TITLE
New navigation (menu), side and event panel layout

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#196]
Requirements and reasons for change:
- current menu gets cluttered on smaller screens
- side menu (info/help) should be resizable (if we keep it) and it should not hide main content action buttons
- event panel needs to resizable as well - #160
- new `system` centric view - so we can go to stats, config, log etc. screens/panels (#151, #152 etc) and option to go back to current `artifact` centric view.

**Comment by DHVAMP** [comment]
A small re-design possibility based on the enterprise edition


[UI-fixes-0.9.3.pdf](https://github.com/magneticio/vamp-ui/files/687315/UI-fixes-0.9.3.pdf)
