### ISSUE TITLE
VGA configuration panel

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#201]
Depends on https://github.com/magneticio/vamp/issues/870 and https://github.com/magneticio/vamp-ui/issues/196
Example of current `katana` style:
![screen shot 2017-01-11 at 22 32 36](https://cloud.githubusercontent.com/assets/7957524/21867304/e737a12c-d84d-11e6-84e8-1092f3fa831b.png)

**Comment by eyal-magnetic** [comment]
Only thing missing here is some testing of the page.
@dragoslav did you get a change to play around with this?

**Comment by dragoslav** [comment]
Try to update few things like info message etc. and if it works, close the issue.
