### ISSUE TITLE
"Embedding" external apps/views inside the main UI

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#206]
There are few examples of Vamp components (workflows, runner etc.) that have their own UI and it would be really helpful to have access to them via main UI.

**Comment by DHVAMP** [comment]
Here is an example as of how I envisioned it for within the enterprise UI. These areas should be composed with the same UI elements as used in the rest of the UI. The content structure for each of them should be created based on the depending app or view. 

![os_external_apps-views-examples](https://cloud.githubusercontent.com/assets/20397075/22248033/08f3264e-e23d-11e6-8121-3ce423e8f370.png)

**Comment by olafmol** [comment]
@jasperjansz can you link the design for workflow webport view?

**Comment by jasperjansz** [comment]
https://zpl.io/zRNPe
https://zpl.io/28QeLb

Full view in new tab: 
https://zpl.io/Vt3Ec
https://zpl.io/Vt3dY

Also have one where it's in one page: 
https://zpl.io/XvASy

Current colors are also in Zeplin just in case: https://zpl.io/cCytk
