### ISSUE TITLE
Add merge action to  blueprints screen

### ISSUE THREAD

**Issue by brniamut** [magneticio/vamp-ui#22]
<a href="https://github.com/dragoslav"><img src="https://avatars.githubusercontent.com/u/7957524?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dragoslav](https://github.com/dragoslav)**
_Wednesday Aug 03, 2016 at 18:32 GMT_
_Originally opened as https://github.com/magneticio/revamp-ui/issues/76_

----

It might be done by specifying name to be as name of the running deployment, but it should be clear not just like a side effect.

**Comment by olafmol** [comment]
In the blueprints screen, a "merge" button is displayed behind every blueprint, and it can be clicked to merge this blueprint to a running deployment. When clicking the button a popup is shown with a small explanation text, and a dropdown list of the running deployments. After selecting a running deployment the user can press the "merge" action button in the popup and the blueprint is merged to the running deployment. There is also a "cancel/close" action to close the popup again without any merge action. Selecting a running deployment is required. The dropdown list of running deployments is alphabetically sorted.
