### ISSUE TITLE
improve UX/UI of configuration panels

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#225]
- how can i change settings?
- what exactly is “applied”?
- what is “flatten”?
- when is a button (f.e. flatten) selected and when not? (ie on/off visual state)
- the on/off switch in logs (sprite?) has some dirty pixels in it
- what exactly does on/off do in the logs?
- sometimes i can select edit, and sometimes i can start typing directly in the editor?
- would it be more efficient to have a dropdown menu to select different views of configuration?
- what’s the difference between “extended info” and configuration? Shouldn’t they show the same?
- is “applied” the same as “generated”?
- i see a lot of overlap, f.e. in “application” and “reference” i see the same settings, what is what, the difference, what is it for? How can i use it? Description, help etc. would really help. Maybe also some kind of hierarchy and a clear visual indication of static view and editable screens?
- in the events panel, what is “allocation”?

**Comment by DHVAMP** [comment]
- This tab should be renamed according to drago
- The applied configuration (which is the only editable option within the backend config)
- Flatten is a different view of the same code. Just flat.
- Fixed
- @eyal-magnetic (dirty pixels?)
- on/off in log makes the interface follow the message or not
- Where can you start typing in the editor without pressing edit first?
- Dropdown Menu? Example? 
- Don't really get the question
- Applied and generated are different. Applied is the same as the actual input and in the generated one vamp makes changes to the template you run.
- This is a question better asked at Drago. Not sure what the exact difference is. 
- Allocation? also ask Drago. It has probably something to do with the active workflow, but i'm not sure to be honest.

**Comment by dragoslav** [comment]
- "... in “application” and “reference” i see the same settings, what is what, the difference, what is it for?" - http://vamp.io/documentation/installation/configure-vamp/
- "what is “allocation”?" - allocation workflow events - generated constantly as health and metrics events
