### ISSUE TITLE
disable/grey-out buttons when action is not available

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#227]
f.e. with "merge" action when there is no running deployment the merge buttons can be greyed out because the action cannot be executed
<img width="789" alt="screen shot 2017-01-30 at 21 38 10" src="https://cloud.githubusercontent.com/assets/355268/22440614/93e8f3a4-e734-11e6-9e39-9ecee8810286.png">
<img width="636" alt="screen shot 2017-01-30 at 21 38 03" src="https://cloud.githubusercontent.com/assets/355268/22440630/9e782f7e-e734-11e6-9356-d16239384090.png">

.

**Comment by eyal-magnetic** [comment]
@olafmol is the second image still happening? i think it is solved already with the "retina display" adaption. And @jasperjansz thinks, and I agree, that action buttons should not be visible when they cannot be used. In this case the "Merge to" button should not appear in the actions section F.E.

**Comment by dragoslav** [comment]
This is already fixed.
