### ISSUE TITLE
increase/decrease arrows are very tiny and close to eachother

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#228]
in f.e. the scale modal the increase/decrease buttons are very close and tiny, and hard to click correctly. 
<img width="549" alt="screen shot 2017-01-30 at 21 40 51" src="https://cloud.githubusercontent.com/assets/355268/22440695/f227c008-e734-11e6-9229-6e585d00b138.png">

**Comment by DHVAMP** [comment]
@eyal-magnetic

**Comment by eyal-magnetic** [comment]
This is only on chrome for mac - its their implementation.
@jasperjansz do we remove them or change their style? 
and i think its refenced in #237 not? if it is we can close this.

**Comment by jasperjansz** [comment]
@eyal-magnetic I don't see a use case for the arrows
