### ISSUE TITLE
UI looks "cramped" on 13" screen

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#229]
f.e. compared to Marathon UI our UI looks cramped, because of font-sizes etc. 

<img width="1246" alt="screen shot 2017-01-30 at 21 43 56" src="https://cloud.githubusercontent.com/assets/355268/22440866/605595f0-e735-11e6-8936-2bc8dc72d330.png">
<img width="1238" alt="screen shot 2017-01-30 at 21 43 41" src="https://cloud.githubusercontent.com/assets/355268/22440892/74e869d4-e735-11e6-8310-307bb294095e.png">

**Comment by olafmol** [comment]
running on 80% font size gives me a much cleaner overview:

<img width="1257" alt="screen shot 2017-01-30 at 21 58 05" src="https://cloud.githubusercontent.com/assets/355268/22441345/4b6e8c58-e737-11e6-91fa-c0a9fd8dee5e.png">

**Comment by DHVAMP** [comment]
still cramped in new build?

**Comment by olafmol** [comment]
yes. @eyal-magnetic will check how to handle Retina (hiDPi) screens with responsive bootstrap.
