### ISSUE TITLE
Remove blueprint from running deployment

### ISSUE THREAD

**Issue by brniamut** [magneticio/vamp-ui#23]
<a href="https://github.com/dragoslav"><img src="https://avatars.githubusercontent.com/u/7957524?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dragoslav](https://github.com/dragoslav)**
_Wednesday Aug 03, 2016 at 18:33 GMT_
_Originally opened as https://github.com/magneticio/revamp-ui/issues/77_

----

**Comment by olafmol** [comment]
In the blueprints overview screen there is a button called "remove" that opens a popup where a dropdown list is shown of running deployments. This way a blueprint can be removed (sliced) from a running deployment. Display and behaviour should be as much the same as merge action

**Comment by brniamut** [comment]
It works but for filtering the list of deployments to choose from I need some advice from Drago.

**Comment by dragoslav** [comment]
It is always unique: cluster + service (breed) name combination. 
Deletion has no effect if:
- deployment has no clusters as blueprint or
- there is no service (breed) among shared clusters that is both in deployment cluster and blueprint cluster

**Comment by brniamut** [comment]
Ok first item was already done. Will fix second item.

**Comment by brniamut** [comment]
So we decided only the first item is good enough for now. Later implementation will implement second item.
