### ISSUE TITLE
UI should show disconnect error message when API backend is not available

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#236]
in the current katana version when the API backend is not available, there should be a red error message/warning, but it's not displayed.

**Comment by eyal-magnetic** [comment]
I've been thinking, if we decide to display an overlay over the entire app maybe we have space also to display some help text in how to solve the issue?

let meknow what you think @olafmol @jasperjansz

**Comment by jasperjansz** [comment]
@eyal-magnetic Yes this is exactly what I have designed so far for this issue. Also, that same design can be used issue #210

**Comment by eyal-magnetic** [comment]
@jasperjansz great!
