### ISSUE TITLE
General Ui points

### ISSUE THREAD

**Issue by jasperjansz** [magneticio/vamp-ui#237]
**Questions/Input needed** @olafmol 

What is the use case of viewing the events stream? Is it necessary for it to take up only half of the screen (viewing stream while on another page)? If not can we put the event stream in the main menu and have it take up a whole page? This will also free up the bottom of the screen for status, etc.

When merging to deployments, is a dropdown the best choice? In other words, can there be so much deployments that the dropdown is hard to use?

Does it make sense to split what used to be called 'tags' into columns so we can add a sorting feature in the table view later?

**Actions**

New background for the logo

Fix alignment. Center: Logo in container 
Vertically: logo & header
Left: Header and table & grid

Button styles consistent throughout. Intuitive colouring for cancel & proceed. Cancel on the left, proceed etc. on the right.

New hover style for buttons

Remove buttons that are disabled unless the user needs to know that the action is an option (no use case for that yet)

Better error message design

Create fixed column spacing for table view for every page

Check consistency of typography

There are inconsistencies between the list and grid view in many cases. E.g. buttons that are active in list view but not in grid view.

In tags, text is not aligned properly and bottom corners aren’t rounded

New design for modal

Put admin panel in the main menu (expanding downward instead of upward)

Add icons in the menu and make the indication which item is active clearer

**Comment by olafmol** [comment]
Please make seperate actionable issues for the open improvements and close this one

**Comment by olafmol** [comment]
closing this, it's not actionable/SMART
