### ISSUE TITLE
List view and artifact tags

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#241]
We don't have any artifact tag attributes thus having `tags` label is misleading.
Possible solutions:
- no `tags` label
- splitting into multiple columns with proper naming

**Comment by jasperjansz** [comment]
I think multiple columns with proper naming is best because it would allow for sorting if we ever add that feature in the future

**Comment by olafmol** [comment]
for now we will remove the tags label as discussed with @eyal-magnetic. Closing this issue. We can re-open later if we have a clear overview on all available attributes and tags.
