### ISSUE TITLE
0.9.2-48-g0809fb1 gateway weight sliders doesn't work

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp-ui#245]
When adjusting the gateway weights in 0.9.2-48-g0809fb1 UI nothing happens when clicking save, adjustments are not saved nor applied.

When adjusting manually through editing the deployment YAML it works as expected.

Possible a websocket timeout, but no notification is displayed.

**Comment by iamtew** [comment]
Same behavior on all configuration settings under the gateway screen, i.e. condition, sticky flag, weight.

**Comment by olafmol** [comment]
it seems to be a AWS specific issue in combination with web sockets, we will debug this after the 093 release @eyal-magnetic

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp/issues/826

**Comment by iamtew** [comment]
Unsure which version fixed it, but I can't reproduce this issue under `0.9.2-75-gf935b9c`.

Closing issue.
