### ISSUE TITLE
admin > log > follow log toggle needs better spacing 

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#248]
the toggle now looks wrong as the text has not enough spacing to the border. I'm also fine with a checkbox instead of toggle, depending on effort to fix this.
<img width="216" alt="screen shot 2017-02-04 at 00 07 20" src="https://cloud.githubusercontent.com/assets/355268/22612216/82f25d4a-ea6f-11e6-8156-a99787a2acc7.png">

**Comment by eyal-magnetic** [comment]
@jasperjansz I've added padding to the toggle text. unless you want to change the component to a checkbox. Let me know
