### ISSUE TITLE
Undeploy does not work 

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#25]
Using blueprint from tutorial step 1, after deploying clicking undeploy gives this message:

“request content was malformed Deployment was not undeployed
Deployment sava:1.0 could not be undeployed. The request content was malformed. Unexpected in DSL: 40000/http”

**Comment by dragoslav** [comment]
This could be something with backend, I'll recheck it.

**Comment by dragoslav** [comment]
I didn't check the source code if the following happens - only way managed to reproduce this is by exporting deployment to blueprint (`?as_blueprint=true`) and then sending it as a delete request body. This is a bug https://github.com/magneticio/vamp/issues/726 on the other hand sending just a plain deployment works without conversion. I don't know what is the reason to convert it, but fixing https://github.com/magneticio/vamp/issues/726 can be sufficient in this case (should work for both deployment and blueprint after the conversion anyway regardless of UI implementation).

**Comment by dragoslav** [comment]
Since https://github.com/magneticio/vamp/issues/726 is resolved, this can be closed also.
