### ISSUE TITLE
Inconsistent color of modal window buttons 

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#258]
For `save` action we use even different colors:

![screen shot 2017-02-05 at 14 01 17](https://cloud.githubusercontent.com/assets/7957524/22626490/f5e0e7a0-ebae-11e6-8306-287147c4905c.png)
![screen shot 2017-02-05 at 14 02 00](https://cloud.githubusercontent.com/assets/7957524/22626495/f5e4c79e-ebae-11e6-98f9-212a3d305cdf.png)
![screen shot 2017-02-05 at 14 02 08](https://cloud.githubusercontent.com/assets/7957524/22626491/f5e193ee-ebae-11e6-9ec2-077481f84ff2.png)
![screen shot 2017-02-05 at 14 02 24](https://cloud.githubusercontent.com/assets/7957524/22626494/f5e29e6a-ebae-11e6-9c9f-8ee56973a37e.png)
![screen shot 2017-02-05 at 14 02 32](https://cloud.githubusercontent.com/assets/7957524/22626492/f5e1f7bc-ebae-11e6-9f98-1530a05f758e.png)
![screen shot 2017-02-05 at 14 02 38](https://cloud.githubusercontent.com/assets/7957524/22626493/f5e2622e-ebae-11e6-99d3-fd85813956c4.png)
![screen shot 2017-02-05 at 14 02 47](https://cloud.githubusercontent.com/assets/7957524/22626496/f5f4ba78-ebae-11e6-8493-93bd37435cc7.png)
![screen shot 2017-02-05 at 14 02 58](https://cloud.githubusercontent.com/assets/7957524/22626497/f5f67aa2-ebae-11e6-8949-c52548846f05.png)
![screen shot 2017-02-05 at 14 03 09](https://cloud.githubusercontent.com/assets/7957524/22626498/f5f67142-ebae-11e6-866e-52aba75a75ad.png)

**Comment by jasperjansz** [comment]
@eyal-magnetic https://zpl.io/Gequj Narrowed down to three colors for primary buttons
