### ISSUE TITLE
2 vertical scroll bars instead of 1

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#260]
VGA configuration template and log pages have 2 vertical scroll bars.

**Comment by dragoslav** [comment]
Version: 0.9.2-65-gef3cc94
![screen shot 2017-02-07 at 08 55 52](https://cloud.githubusercontent.com/assets/7957524/22682518/4f89a232-ed13-11e6-9978-df71ca423bc2.png)

![screen shot 2017-02-07 at 08 55 08](https://cloud.githubusercontent.com/assets/7957524/22682493/2f4728d2-ed13-11e6-99f8-96c6c5d91339.png)

**Comment by eyal-magnetic** [comment]
Logs is the only place where we have the scroller inside the content. Is should not, however, display the other scroller.

I cannot repro this on:
VERSION	0.9.2-85-gb8350ee
UI VERSION	0.9.2-2-g7197b99

Can you install latest and check again?

**Comment by eyal-magnetic** [comment]
Clsoing this for now

**Comment by dragoslav** [comment]
Outer scroll bar is due to overall page height (margin, padding or something similar). It's present in Firefox and Chrome, but not in Safari. In Firefox it is just more prominent (screenshot) due to scroll bar style. Scroll bar style we can change or not, but again this is about having 2 instead of one single scroll bar.

**Comment by eyal-magnetic** [comment]
Was a problem with the log view specifically. Should be ok now.
