### ISSUE TITLE
No option to see the whole error message

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#262]
0.9.2:

![screen shot 2017-02-05 at 18 00 07](https://cloud.githubusercontent.com/assets/7957524/22628066/7534b432-ebcd-11e6-84cc-85a3f514e98d.png)
![screen shot 2017-02-05 at 18 00 16](https://cloud.githubusercontent.com/assets/7957524/22628067/763f6f3e-ebcd-11e6-8887-51c9d13a26f1.png)

Now:

![screen shot 2017-02-05 at 18 03 01](https://cloud.githubusercontent.com/assets/7957524/22628071/7f336f64-ebcd-11e6-99c3-45d5660394c2.png)

**Comment by eyal-magnetic** [comment]
I think this needs a better UI @jasperjansz what do you think? why would someone to want to see the whole message right away?

**Comment by eyal-magnetic** [comment]
Reverting back to 0.9.2 behaviour until we start with the new design.

@olafmol @dragoslav @jasperjansz
