### ISSUE TITLE
Template editing (VGA configuration) doesn't follow common button pattern

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#263]
Buttons are disabled by default until template is edited:
![screen shot 2017-02-05 at 18 19 05](https://cloud.githubusercontent.com/assets/7957524/22628185/d284f7ee-ebcf-11e6-9e3f-c6f6b9331e64.png)

Common pattern is not to have disabled buttons. In case of artifact editing we enable `save` after a change. In case of backend configuration there is an explicit `edit` button.

**Comment by eyal-magnetic** [comment]
Right now of these buttons will follow the common button rule the will not appear and so the user will not be aware that he is actually it an "edit" mode.

I suggest we leave it as is right now and once we have the new "start editing" mode behaviour we can remove these buttons.

@jasperjansz  @dragoslav
