### ISSUE TITLE
Artifact editing and cancel button

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#264]
Since disabled buttons are now not shown (in this case`save` button), it's not clear what we are canceling. This page is not only for editing but the full definition view (inspection). It would be helpful if:
- there is an `edit` label (e.g. `Edit sava/1.0`), so `cancel` makes more sense
- or to have `back to list` instead of `cancel` (or no buttons at all), and if content is changed then to have both `save` and `cancel`

![screen shot 2017-02-05 at 18 23 45](https://cloud.githubusercontent.com/assets/7957524/22628248/158d1688-ebd1-11e6-8a6b-23bf758af56e.png)

**Comment by eyal-magnetic** [comment]
Since "back" and "cancel" are effectively the same action i would say adding "Edit ...." to the title makes more sense. 
@gggina 
@jasperjansz

**Comment by olafmol** [comment]
We decided: any editor needs a specific "edit" button to switch into edit mode, and then when in edit mode provides save and cancel options.

**Comment by eyal-magnetic** [comment]
For 0.9.3 solution is to add "Editing ... " in title area to give it more context.

Solution will be with new edit mode as described in #263
