### ISSUE TITLE
Ordering/sorting of columns by clicking on column header name does not work

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#27]

**Comment by brniamut** [comment]
@dragoslav Is this supported by the backend? Can't find anything in the documentation. No problem to do it frontend only for now but just curious.

**Comment by brniamut** [comment]
Closed by mistake

**Comment by brniamut** [comment]
We removed it from the frontend. When sorting is suported in backend we will look again at this issue.
