### ISSUE TITLE
in detail screens the status first shows red/undeployed

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#28]
when switching to a detail screen first a "negative" status is shown by default (red circle, undeployed etc) before switching to the real status after a few seconds. It would be less scary/much nicer if we either see a neutral screen, a loader/spinner, or cache the latest status and show this before updating with the latest realtime status after polling

**Comment by brniamut** [comment]
Loading bar was removed because of caching solution. Does not implement te eventstream yet. So you get values that are not there yet.
