### ISSUE TITLE
when making browser fonts smaller in chrome in workflows list view, buttons increase

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#284]
when f.e going to 80 or 90% fontsize in the browser, the workflow title stays the same size, and the button size increases. I would expect these items to become smaller.

**Comment by eyal-magnetic** [comment]
Should be fixed by 2145a07dab5ad0df51e7531a33c0f5db2e2546ff or the layout changes we did for the gridview. And the fact we dont have buttons in the grid item anymore.
