### ISSUE TITLE
Info panel additional fields

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#29]
currrently missing in the info panel:

- "hello" message
- time Vamp has been running

**Comment by dragoslav** [comment]
Just built the latest, and there are no values:

![screen shot 2016-08-14 at 13 45 00](https://cloud.githubusercontent.com/assets/7957524/17648886/60d8a886-6225-11e6-8c52-bd19e5f2736b.png)

Not sure if it was broken meanwhile.

**Comment by brniamut** [comment]
Rookie mistake #1, changed the controller of the .tmp file instead of the current one. Mistake has been fixed again. 

![alt text](http://lionsofliberty.com/wp-content/uploads/2014/03/doh-homer-simpson.jpg "Doh")
