### ISSUE TITLE
referencing long gateway route conditions screws up formatting

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#291]
in the gateway detail screen when i use a long condition string, or reference a condition with a long string, i cannot edit my condition anymore as the string is overflowing over the edit icon and also over the condition strength edit icon and column.

**Comment by bloeder** [comment]
This is fixed when using a normal resolution to view the page.
The issue is reproducable whit smaller resolutions as the page is not responsive.
For now regarding this issue as solved

**Comment by bloeder** [comment]
Ok I noticed that some have a smaller resolutions and this problem still occurs.. will re-open and solve this issue
