### ISSUE TITLE
Standardize UI

### ISSUE THREAD

**Issue by eyal-magnetic** [magneticio/vamp-ui#293]
Current UI - Css and layout is a hybrid of a couple of different designs. 
Need to standardize the entire UI according to new design made by @jasperjansz this includes:
- Menu and navigaiton upgrade
- Better header and action buttons separation 
- New panels layout - additon of a collapsable right panel
- Css style chages to colors, buttons, modals, inputs

**Comment by olafmol** [comment]
closing this, splitting into separate issues
