### ISSUE TITLE
Menu improvements

### ISSUE THREAD

**Issue by eyal-magnetic** [magneticio/vamp-ui#296]
- [x]  Brand and logo
- [x]  Styling: Grouping , Collapse and expand, Icons, Element states
- [x]  Support of link grouping or sections
- [x]  Horizontal collapsing

**Comment by olafmol** [comment]
for reference please use this theme: https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S

**Comment by jasperjansz** [comment]
https://zpl.io/2sLBGC

**Comment by olafmol** [comment]
closing this as it's merged.
