### ISSUE TITLE
Add service detail view

### ISSUE THREAD

**Issue by eyal-magnetic** [magneticio/vamp-ui#298]
Service level page displaying service data and instances list.

**Comment by olafmol** [comment]
@jasperjansz can you link the design?

**Comment by jasperjansz** [comment]
https://zpl.io/Z1PHeEU

**Comment by eyal-magnetic** [comment]
Fixed by 254ef068f0a565843e7bf512af8ec070c0a4ca96

**Comment by eyal-magnetic** [comment]
@olaf regarding the last point you mentioned, it seems redundant to have the ports clickable since the page they should refer to is the "instance" page to which the name lable already refers.

**Comment by olafmol** [comment]
@eyal-magnetic ok, let's move this discussion to broader UX improvements we will plan a brainstorm for. So we can close this issue.
