### ISSUE TITLE
Update the rest-api URL

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp-ui#3]
It would be nice to be able to update the rest-api url via the web-interface. Or give visual feedback that the url has been updated. Especially since the default is port 8080.

**Comment by danielsneijers** [comment]
Hi Josh,




This is currently implemented in the next version of the UI, which will be probably rolled out this week. If you feel adventurous you could check out the development branch of vamp-ui, which already has the option of changing the API Url manually trough the interface. If you have any further questions I'd be happy to help.

**Comment by JoshFalken** [comment]
Thanks Daniel! I checked out the latest development branch and also like the color scheme of the options pane in that branch. Will wait for the release and close this issue.
