### ISSUE TITLE
Improve usability docker-compose to blueprint transformation 

### ISSUE THREAD

**Issue by ThomasMeijers** [magneticio/vamp-ui#301]
We need to find a way to make the docker-compose to Blueprint transformation more user friendly. 

Suggestions for possible improvements:

*  Selecting conversion of a docker-compose file differently.
*  Providing the name of the Blueprint differently than the input form.
*  Ports that are created from environment variables assume that the port is of type Http even though this could be Tcp. We need some interactive way of letting the user specify what kind of ports they are.
*  An interactive way of confirming the made transformations.

**Comment by olafmol** [comment]
@jasperjansz can you add a design and UX implementation for a first minimal implementation of adding a "upload docker compose" option in the UI in the blueprint section.

**Comment by olafmol** [comment]
after discussion with @jasperjansz:

the docker-compose button should become a checkbox with label "Docker compose format", positioned to the left (aligned with editor below), checking the box displays name field to right of checkbox/label, we keep the save button is in same position as it is right now (to the right). 
Save button is disabled/greyed out when a name is entered in the form field.
