### ISSUE TITLE
Redesign workflow card

### ISSUE THREAD

**Issue by eyal-magnetic** [magneticio/vamp-ui#320]
- [x]  Alignments
- [x] Webport links 
- [x] Remove buttons

**Comment by olafmol** [comment]
@jasperjansz what is the consistent design for clickable links? right now the webport is not underlined and at mouse-over its changing colour, not showing an underline. Currently its not evident one can click on this link, so we need to improve this and have a consistent way of clickable links. Please advice

**Comment by eyal-magnetic** [comment]
Relates to #331
