### ISSUE TITLE
service instance detail page issues

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#325]
- [x] both stdout and error log does not show in katana quickstart, it only shows a "[]"
- [x] the breadcrumb colour is not right, the cluster part is more bright/white than the last service part (which should be highlighted but isn't)
- [x] the webport tab shows the content cluttered, not as we see in the right panel when clicking webport from the gateway detail screen (see screenshot 
<img width="1085" alt="screen shot 2017-03-15 at 21 45 58" src="https://cloud.githubusercontent.com/assets/355268/23970123/190739a4-09c9-11e7-9777-fb4b3d8fc193.png">

additional improvements:

- [x] enable scrolling inside the webport view when page is higher 
- [x] add "breakout" link in the webport and json views that opens these views in a seperate tab (like the breakout link in the right panel)

**Comment by eyal-magnetic** [comment]
@olafmol 
Point 1 is due to CORS (please verify you are running the ui of the same host as the rest of the deployments)
Points 3 and 4 you mentioned depends on implementation of inner page on small viewports.
Rest are fixed
