### ISSUE TITLE
Combine toasters

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#33]
don't show multiple toasters with the same message, combine them

**Comment by dragoslav** [comment]
Check https://github.com/magneticio/vamp-ui/commit/d1031d478cd84fef26eaa03d933df92dee8f3370#commitcomment-18580767

**Comment by brniamut** [comment]
You are right. The option was not documented in the angular implementation and I tought this was the quickest solution. I will fix this asap.
