### ISSUE TITLE
When there are more than 1 workflow instance running, it is not clear that ports belong to different instances

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#331]
2 instances of log workflow:

![screen shot 2017-03-17 at 16 11 24](https://cloud.githubusercontent.com/assets/7957524/24049466/69b7f26c-0b2c-11e7-85dc-a8f3efd202d8.png)

**Comment by eyal-magnetic** [comment]
@olafmol @dragoslav @jasperjansz 
What would you have written instead?

**Comment by eyal-magnetic** [comment]
Wrong issue reference in commit

**Comment by eyal-magnetic** [comment]
Currently showing port number. Will be changed and restyled once we re-imagine the cards
