### ISSUE TITLE
List view - items in one row

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#332]
UI version `0.9.3-44-ga532d2f`, Chrome:

![screen shot 2017-03-17 at 16 16 03](https://cloud.githubusercontent.com/assets/7957524/24049715/26858ce2-0b2d-11e7-95e7-1f24461ac5a7.png)

**Comment by eyal-magnetic** [comment]
Closing. Solved in 4106bf6ab2b81fcf0c77ef439e7367747b746851
