### ISSUE TITLE
Backend configuration not visible in UI

### ISSUE THREAD

**Issue by gggina** [magneticio/vamp-ui#335]
http://192.168.99.100:8080/#/admin/configuration
See screenshot below - it's the same for all tabs. This is the version I'm running:
```
Hi, I'm Vamp! How are you? 

RUNNING SINCE	20-03-2017 10:16:47
VERSION	0.9.3-80-gaf35608
UI VERSION	0.9.3-36-gb4c4a9c
PERSISTENCE	zookeeper
PULSE	elasticsearch
KEY VALUE STORE	zookeeper
GATEWAY DRIVER	haproxy
CONTAINER DRIVER	marathon
WORKFLOW DRIVER	marathon, chronos
```
![screen shot 2017-03-20 at 14 23 15](https://cloud.githubusercontent.com/assets/3646450/24101593/395c6aea-0d79-11e7-884a-d044e1126e3d.png)

**Comment by eyal-magnetic** [comment]
Closed by b86fb82a47b431d5d0f55a34ca48e7f28e280cbb
