### ISSUE TITLE
log view shows very little events

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#336]
normally it's very "busy" especially when enabling trace and info, now it shows almost nothing in the logs

**Comment by dragoslav** [comment]
This could be also bug on server side. Locally (dev) I use different configuration, so don't really check this, but we could verify using just API endpoints if log events are streamed or not.

**Comment by eyal-magnetic** [comment]
@dragoslav im actually not getting any messages while listening to - $scope.$on('/log', function (e, response) 

Did anything change in the backend?

**Comment by dragoslav** [comment]
Fixed by https://github.com/magneticio/vamp/commit/b488555cf4762b4060a17dc9bdb5f1c9f39fab86
