### ISSUE TITLE
Second instance port (tab) gives an error

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#338]
Version 0.9.3-61-ga6a7c84

![screen shot 2017-03-21 at 14 48 52](https://cloud.githubusercontent.com/assets/7957524/24150277/9b47824a-0e45-11e7-826b-f83179335f5e.png)
![screen shot 2017-03-21 at 14 48 56](https://cloud.githubusercontent.com/assets/7957524/24150278/9c38dbf4-0e45-11e7-92e3-79b96011df79.png)

**Comment by eyal-magnetic** [comment]
Closed by d349951f14d7d2f11279a2a3c265da2c2d4dc423
