### ISSUE TITLE
alignment and font size issues in workflow log views

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#344]
in all browser on my MBP 13" retina the positing and size of the workflow log view seem to "cramped" due to a big font, so all info is not displayed correctly and alignment is not nice. I suspect a smaller font would work here to fit everything in and not break lines to much and thus keeps alignment better. (f.e.the same font size as the revisions list, or as the labels in the grid cards)

Screenshots:

<img width="797" alt="screen shot 2017-03-23 at 09 31 51" src="https://cloud.githubusercontent.com/assets/355268/24238827/dc518008-0fab-11e7-8b2c-6b1b430a6d35.png">

(see right label dissapear behind other columns and be positioned higher than others)

<img width="556" alt="screen shot 2017-03-23 at 09 32 05" src="https://cloud.githubusercontent.com/assets/355268/24238841/e30f8ef8-0fab-11e7-832d-56a358ecb53a.png">

(see alignment of top bar "execution log" title, compared to "back" link)

<img width="226" alt="screen shot 2017-03-23 at 09 35 52" src="https://cloud.githubusercontent.com/assets/355268/24238954/4b77cf14-0fac-11e7-98da-719f8c476e7b.png">

(see how http response label breaks to next line and flows through other text)

**Comment by olafmol** [comment]
in safari the issue persists with the right column positioning

**Comment by eyal-magnetic** [comment]
Closed by 65ae600ef187750d599253f956daea7f48ee3005
