### ISSUE TITLE
cluster view list doesn't alway show right number after scaling

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#347]
when scaling a service in the cluster view, the right number of instances is shown correctly after some time. Now when i click on one of the instances, and then go back to the cluster view, the old number of instances is shown. It seems to be some caching thing in Vamp UI, as i have disabled my browser cache. After refreshing the browser window the correct amount is shown again.

**Comment by eyal-magnetic** [comment]
@olafmol you meant service view i assume?

**Comment by olafmol** [comment]
Yes indeed

**Comment by eyal-magnetic** [comment]
Due to issue with breadcrumb. Will get to it after release.

**Comment by eyal-magnetic** [comment]
Fixed by 5b1c8aafc27a1af573eab021c565a1cc9b252478
