### ISSUE TITLE
deployed status label size is to high with certain service names

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#348]
f.e. with blueprint from our 3th tutorial i see this, ie the status labels break to the next line making them squares instead of labels

<img width="1081" alt="screen shot 2017-03-23 at 10 11 33" src="https://cloud.githubusercontent.com/assets/355268/24240392/b19feab0-0fb1-11e7-9347-af04ef6e2e7e.png">

**Comment by olafmol** [comment]
re opening. status in deployment detail screen is now gone, only spinning cog

<img width="573" alt="screen shot 2017-03-23 at 15 22 05" src="https://cloud.githubusercontent.com/assets/355268/24252086/b9d11f94-0fdc-11e7-855c-b7ffa8f305bd.png">

**Comment by eyal-magnetic** [comment]
We didnt show a status before either, I dont understand.

**Comment by olafmol** [comment]
It looks strange that a status label can wrap to two lines, as we control the text labels inside

**Comment by olafmol** [comment]
Closing this as the solution with only a spinner when updating is ok
