### ISSUE TITLE
cancel button displayed off-screen with error message

### ISSUE THREAD

**Issue by gggina** [magneticio/vamp-ui#351]
MacBook Pro (Retina, 13-inch) 
<img width="1280" alt="screen shot 2017-03-23 at 13 31 09" src="https://cloud.githubusercontent.com/assets/3646450/24247760/37fde5ba-0fcd-11e7-8443-1c009cf8ea31.png">

**Comment by eyal-magnetic** [comment]
Closing due to a hacky fix for now
@jasperjansz we really need to find another way of displaying these error messages
