### ISSUE TITLE
Displaying instance log 

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#352]
After adding a new `host:port` proxy endpoint (`/proxy/host/{host}/port/{port}/`, https://github.com/magneticio/vamp/issues/912) and using it, log is not displayed.
In addition `stdout/stderr` tabs could be added after the port tabs.

**Comment by eyal-magnetic** [comment]
Solved in 74554f85e111da41554cf00174537b4f60796d6c
