### ISSUE TITLE
certain browser window size doesn't show help icon

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#355]
katana on all browsers

<img width="608" alt="screen shot 2017-03-23 at 15 03 05" src="https://cloud.githubusercontent.com/assets/355268/24251892/f8f46baa-0fdb-11e7-8323-ddf5db697abb.png">

**Comment by gggina** [comment]
for me it happens around 1425 or 1206 (depending on the screen monitor/macbook)
