### ISSUE TITLE
Text in gateway box overlaps

### ISSUE THREAD

**Issue by ItsMeijers** [magneticio/vamp-ui#361]
On linux mint chrome the text of a gateway box overlaps (see screenshot)

![gateway_text_overlay](https://cloud.githubusercontent.com/assets/4912941/24351421/e13f9766-12e5-11e7-8dc8-2bb45ebb97e2.png)

**Comment by jasperjansz** [comment]
related to #384

**Comment by bloeder** [comment]
Fixed but not closed.
Now card grows with content.
