### ISSUE TITLE
condition strength slider reaches end of route box

### ISSUE THREAD

**Issue by gggina** [magneticio/vamp-ui#362]
![screen shot 2017-03-27 at 15 23 41](https://cloud.githubusercontent.com/assets/3646450/24358465/7a9f0368-1301-11e7-8339-606ac900c9d3.png)

**Comment by eyal-magnetic** [comment]
@jasperjansz  keep this in mind for the Gateways page redesign

**Comment by bloeder** [comment]
Fixed
