### ISSUE TITLE
Show events from Vamp

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#37]
There should be a panel/page showing all events coming from Vamp (`api/v1/events/stream`):
- collecting event always (e.g. in service)
- keep just last 50 or so and display them on separate page

**Comment by dragoslav** [comment]
Similar to https://github.com/magneticio/vamp-ui/issues/57, it's not enough to show a blank page first and then wait for new events, but we should show past 50 or 100...

**Comment by olafmol** [comment]
have to "prime" the cache when initiating UI

**Comment by brniamut** [comment]
Now starts polling when app is opened for the first time.

**Comment by brniamut** [comment]
We want the first 50 when loading the page firs.

**Comment by olafmol** [comment]
Last 50

**Comment by brniamut** [comment]
@dragoslav Is there a restfull call to the events endpoint that will give me the last 50 (or whatever) I can't seem to find it in the documentation. Even the latest one.

**Comment by olafmol** [comment]
I would expect the order of the events to be displayed in reverse order, ie latest on top, new events added above

**Comment by olafmol** [comment]
event panel seems to slide over the page info, it should push the info above to a smaller size instead. Ideally i would also like to resize the height of the events panel

**Comment by olafmol** [comment]
Closed events-bar is positioned over info of deployment detail screen, so some lines of data cannot be seen or edited

**Comment by dragoslav** [comment]
@brniamut did you try to use `page` and `per_page`? It should work using them.

**Comment by brniamut** [comment]
I see this as a few issues:
* [  ] Change order of events
* [  ] Info panel should become shorter when opening deployments panel
* [  ] Push data above the panel upwards
* [  ] Implement page and per_page
