### ISSUE TITLE
when Vamp backend is unavailable UI shows broken image

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#378]
when the backend is gone, the UI shows a message that it cannot connect to the backend, but above this message is a broken image, we should either point to an image that is available somewhere so it's not broken, or not show an image

**Comment by eyal-magnetic** [comment]
@olafmol On what build does this happen and if you can write step to reproduce it will help a lot. 
Thanks

**Comment by olafmol** [comment]
it happens when disabling browser-cache. Logically it cannot find the image anymore when the backend service is not available (stopped) and thus not serving any assets like the image. Closing this issue.
