### ISSUE TITLE
Text extending outside card

### ISSUE THREAD

**Issue by jasperjansz** [magneticio/vamp-ui#384]
![screen shot 2017-04-18 at 17 04 52](https://cloud.githubusercontent.com/assets/25477905/25137836/332bcbf6-2459-11e7-830a-3c2c6f157271.png)
<img width="483" alt="screen shot 2017-05-03 at 10 06 35" src="https://cloud.githubusercontent.com/assets/25477905/25652387/42016592-2fe8-11e7-8e86-6627058bc14a.png">

**Comment by jasperjansz** [comment]
makeup of the card: https://zpl.io/1SnUvz

What happens when text becomes too long? Truncate and show tooltip (https://zpl.io/Z15nepN) on hover.

**Comment by bloeder** [comment]
Fixed but not closed.
* titles are properly truncated
* card  grows with content
