### ISSUE TITLE
Remove autoclose from toasters

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#39]
i would like to keep the toasters open, so manually close/dismiss them. Especially for error warnings this is relevant.

**Comment by brniamut** [comment]
Already implemented, see commit: ab82faa074f81e0e33a9ae9d8892f7c9157ccbda

**Comment by dragoslav** [comment]
If quick-start is stopped and UI still open in browser, duplicate error messages appear: "Can't connect to Vamp". Maybe there is a bug in library?

**Comment by olafmol** [comment]
browser seems to choke
