### ISSUE TITLE
horizontal scroller in editor views

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#393]
i get a horizontal scroller in all editor screens, it seems to be a few pixels to wide (tested in safari, chrome and FF on mac OS X Yosemite)
<img width="1228" alt="screen shot 2017-05-05 at 14 02 06" src="https://cloud.githubusercontent.com/assets/355268/25744922/b3deaeb2-319c-11e7-80b6-c7852c06d331.png">

**Comment by eyal-magnetic** [comment]
@olafmol did you increase the browser font size?
