### ISSUE TITLE
UI chokes on larger blueprints and deployments

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#396]
using the sava-big-2121.yml blueprint the Vamp UI seems to choke on the contents. Saving blueprint times out sometimes, exporting the deployment of it to blueprint consistently throws an error or timeout, often the UI says that the blueprint of deployment cannot be found anymore etc.
When doing the same actions directly on the API the response is very fast and good. It seems the UI chokes on the data of this blueprint/deployment.

**Comment by eyal-magnetic** [comment]
@olafmol where do we stand on this?

**Comment by olafmol** [comment]
It seems to be more of a backend issue where timeouts and overflowing of events stalls the API. Closing this for now. We still have the issue in the UI with the log streams crashing browser though.
