### ISSUE TITLE
UI shows "deployment deleted in background" popup when disconnected from marathon/mesos

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#406]
when f.e. doing a ZK or marathon restart, or having a disconnect, often(always?) the UI displays a "the deployment has been deleted in the background" message, which is incorrect, as only the connection is (temporarily) not available. It should check if there is a connect first, and only if there is a connect, and the deployment is not there anymore, display this error.

**Comment by bloeder** [comment]
according to @jason-magnetic-io this is an old issue and should not occur anymore. Hasn't been seen in a while now. closing...
