### ISSUE TITLE
collapsable menu needs to be rethought

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#428]
the current collapsable menu implementation doesn't work well, menu items like admin > logs are not visible because they are hidden behind the collapse menu bar, positioning seems to be off with text showing through below etc. Also the default behaviour of being collapsed by default is not good, as it's harder for people to understand all the options without menu labels.

Common best practices seem to position a collapse option on top, we need to redesign the UX here. 

Labeling this as a bug as the log menu item cannot be clicked.

<img width="241" alt="screen shot 2017-08-31 at 10 30 52" src="https://user-images.githubusercontent.com/355268/29914233-0dcceaf4-8e38-11e7-8f76-b59aaf07687e.png">
<img width="412" alt="screen shot 2017-08-31 at 10 30 26" src="https://user-images.githubusercontent.com/355268/29914234-0df7b96e-8e38-11e7-988c-33d8aaf10d45.png">
<img width="483" alt="screen shot 2017-08-31 at 10 30 14" src="https://user-images.githubusercontent.com/355268/29914235-0dfbd4ae-8e38-11e7-87d0-d892c5c2c4bb.png">

**Comment by jason-magnetic-io** [comment]
This issue is blocking the EE UI branding

**Comment by jason-magnetic-io** [comment]
We may need to update the automated tests after this is fixed, magneticio/vamp-ui-rspec#7

**Comment by olafmol** [comment]
In the latest DCOS katana build (0.9.5-1237-g7000ce10)
i cannot reproduce this issue anymore, UI hash is UI version 0.9.5-22-g27b1446 The collapse menu-option now has enough spacing and moves down correctly in Chrome, Safari and FF. Closing this.

**Comment by olafmol** [comment]
the most recent docker "master" tag version of vamp-dcos seems to have the UI issues with collapsing, so we need to check what version is going into the latest stable docker package. Katana version seems to have the good behaviour regarding collapsable menu.
