### ISSUE TITLE
display BE & UI version on info panel

### ISSUE THREAD

**Issue by cristifilip** [magneticio/vamp-ui#433]
Display the versions in UI. Currently the version is visible only for super-admins, but for CE version it has to be displayed by default.

**Comment by olafmol** [comment]
Re-opening as we need to verify an integration test against a specific (Docker) repo:tag. Please report the tested repo(s) and tags.

**Comment by cristifilip** [comment]
tested on `vamp-docker:katana`

**Comment by jason-magnetic-io** [comment]
@cristifilip has this been merged to KPN? I don't see it in the build from yesterday
