### ISSUE TITLE
Deployment - if new name is chosen, old (blueprint) name appears in the list and gets replaced after polling refresh

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#56]

**Comment by dragoslav** [comment]
If I do "merge to" and go to deployment page the same thing happens again - I get a blueprint name and then eventually is turned to deployment name.

**Comment by dragoslav** [comment]
With new blueprint deployment (`deploy as`) still need to wait for polling refresh to get created deployment.

**Comment by olafmol** [comment]
Deploy as works as expected (=fine), merge to shows blueprint-name of new blueprint in deployment overview first, then refreshes correctly after polling. Need to show running deployment name, also after merge to action.
