### ISSUE TITLE
Chart data are reset when another page is visited

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#57]
Two solutions:
1) data can be collected in background and displayed from that storage. Check out also https://github.com/magneticio/vamp-ui/issues/37 - these two issues can be easily combined.
2) just query events `/api/v1/events` and get let's say last 25 or whatever size is required and then on new events just update chart as usual.

**Comment by brniamut** [comment]
Backend doesn't seem to work with events right now. De docker machine already has more that 4 gig memory. See issue: https://github.com/magneticio/vamp/issues/732
