### ISSUE TITLE
Option to set stickiness

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#63]
Now we just show (read-only) but why not then to have an option to set it (e.g. a drop-down)?

**Comment by brniamut** [comment]
Does sticky only have two options (Sticky and not Sticky)?

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp.io/blob/develop/content/documentation/using-vamp/sticky-sessions.md

**Comment by olafmol** [comment]
the same could be useful for "balance" type
