### ISSUE TITLE
Can't save two blueprints with the same name

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp-ui#7]
I can't add a blueprint when the name has already been assigned to a different blueprint. This could be by design but if that's the cause it would be nice to have a message when I press the 'save' button. The 'save'-button now just doesn't seem to work.

You can easily reproduce this by adding the same blueprint twice (or trying to add it anyways).

**Comment by danielsneijers** [comment]
Hi Josh, 

Thanks for the heads up, this little bug slipped trough I guess. I now added a check for duplicate names when creating blueprints or breeds and pushed it to our development branch. It will be included in the next release.

**Comment by JoshFalken** [comment]
@danielsneijers also great! BTW, I checked out the development-branch and really like the way you can change the weight in this release.
