### ISSUE TITLE
Fix Javascript errors in deployment detail screen

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#76]
when in deployment detail screen there is a javascript error that explodes (999+ times in console errors). Its seems to be in:

function updateWorkflowController

vendor-bf8671f90d.js:5711Error: undefined is not an object (evaluating 'e.substring')
g@http://192.168.99.100:8080/scripts/app-dd4f13a3bc.js:1:6721
fn0
http://192.168.99.100:8080/scripts/vendor-bf8671f90d.js:33:2693
$digest@http://192.168.99.100:8080/scripts/vendor-bf8671f90d.js:33:11028
$apply@http://192.168.99.100:8080/scripts/vendor-bf8671f90d.js:33:12699
http://192.168.99.100:8080/scripts/vendor-bf8671f90d.js:33:20154
o@http://192.168.99.100:8080/scripts/vendor-bf8671f90d.js:31:22675
http://192.168.99.100:8080/scripts/vendor-bf8671f90d.js:31:24133
vendor-bf8671f90d.js:5711Error: undefined is not an object (evaluating 'e.substring')
g@http://192.168.99.100:8080/scripts/app-dd4f13a3bc.js:1:6721

**Comment by brniamut** [comment]
I am not able to reproduce the error. Not with the development version, not with the latest build version. Tested on Chrome, Firefox and Safari. Maybe this only happens with a certain deployment.

**Comment by brniamut** [comment]
Error does not occur anymore.
