### ISSUE TITLE
Possible enhancements

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp-ui#8]
Just a few possible enhancements to UI:

- [x] The possibility to undeploy a number of deployments simultaneously (with checkboxes or something like that)
- [x] The possibility to delete breeds
- [ ] The possibility to see the request/response that was done/received to Vamp.

**Comment by brniamut** [comment]
Hey Josh,

The possibility to undeploy a number of deployments is not yet available in the 0.9.0 ui, I will deliberate with the team if we want to add this feature. I like it but it needs a rethinking of the UI

The possibility to delete breeds is added in version 0.9.0

The possibility to see the request and response is not there in 0.9.0. I don't see that as an important part of the UI, as you can always look at the networks tab in your browser. But this is open for discussion. 

I will leave this issue open so we can discuss the features and make a decision.

**Comment by JoshFalken** [comment]
Hey Bastiaan,

To clarify the last point regarding the request/repsonse: what I meant was the REST-call to VAMP. The use case is the following: when learning to work with a new API it's always nice to see the calls that an working application is making. This speeds up the building of custom applications. 

AFAIK the actual REST-call to VAMP doesn't show up in the network tab. But I could be wrong (didn't look there when I wrote this possible enhancement)

**Comment by dragoslav** [comment]
First 2 points are implemented in coming `0.9.1` release. 
Logging traffic (on/off switch) will be added as part of https://github.com/magneticio/vamp-ui/issues/151 - in `0.9.1` you can set debug mode during build https://github.com/magneticio/vamp-ui/tree/ws#release & https://github.com/magneticio/vamp-ui/blob/ws/environment.sh.
