### ISSUE TITLE
Disable weight editing when only 1 service in cluster

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#88]
If there is only 1 service in a cluster it has no use to enable the weight editor/popup.

**Comment by olafmol** [comment]
the "edit" icon is not clickable to edit weight, only the weight label text. This is incorrect, the edit icon should be clickable, and the weight label text not

**Comment by brniamut** [comment]
- [ ] Only icon clickable
- [ ] No weight editor when only one service
