### ISSUE TITLE
Suggestion: support for pagination

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp-ui#9]
VAMP-ui doesn't support pagination as of yet. So it just shows the first 30 deployments (and probably breeds & blueprints) on their pages. It would be nice to have pagers to view the next 30.

**Comment by danielsneijers** [comment]
We're freezing any new features with the upcoming release of version 7.10, but I will pick this up in the next sprint as it definitely is something that should be in the UI. We'll keep you updated on any progress.

**Comment by dragoslav** [comment]
Resolved in 0.9.0.
