### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#92]
https://travis-ci.org/magneticio/vamp-ui/builds/152991986
Error: File not found with singular glob: bower_components/components-font-awesome/css/font-awesome.css

**Comment by olafmol** [comment]
on my local quickstart build i get this message, not sure if it is an error and/or related?

"building docker image: magneticio/vamp-quick-start:0.9.0 
Sending build context to Docker daemon 64.64 MB
Step 1 : FROM magneticio/vamp-clique-zookeeper-marathon:0.9.0
 ---> a73da0b4fe21
Step 2 : RUN mkdir -p /usr/local/vamp
 ---> Using cache
 ---> 72d1f692941d
Step 3 : ADD ui.tar.bz2 vamp.jar application.conf logback.xml vamp.sh /usr/local/vamp/
lstat ui.tar.bz2: no such file or directory
done.
MacBook-Pro-5:vamp-docker olafmol$

**Comment by dragoslav** [comment]
Yes, it can't build UI. This script can be improved to fail immediately, but anyway it's the same thing.

**Comment by brniamut** [comment]
I'm on it!

**Comment by brniamut** [comment]
Forgot to add the font-awesome dependency to the bower.json.

**Comment by dragoslav** [comment]
@brniamut did you get any notification from Travis-CI? I didn't get any and that's strange. Issues like this one Travis-CI should report...
